#!/bin/bash
#current JSON data being processed is stored in a file called api_data.json
# $API_DATA_FILE parameter can be used to access it
# e.g. cat $API_DATA_FILE
# if modifying the data make sure to write it back to the same file name and location
# The following script modifies a swagger.json file to add the additionaly wrapper required by the zap scanner
echo "running customisations"
cp "${API_DATA_FILE}" "temp_data.json"
node one-pipeline-config-repo/scripts/zap/zap-custom-scripts/generate-definitions.js $(pwd)/"temp_data.json" > "${API_DATA_FILE}"
rm temp_data.json
# cat "${API_DATA_FILE}"

